// Lane Failover Monitor for TOU
// Implements §8 monitoring: detects quota‑related errors and runs stuck > 15 min.
// Updates the persistent JSON state at ~/.config/ceridorio/paperclip-tou/lane-failover-state.json
// and prints a concise summary. Intended to be invoked by the CFO agent (or manually).

import fs from "node:fs/promises";
import path from "node:path";
import { db } from "@paperclipai/db"; // Adjust if db export differs
import { agents, heartbeatRuns } from "@paperclipai/db/tables";
import { eq, and, gte, lt, inArray } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Types matching the JSON schema (partial – only fields we write).
// ---------------------------------------------------------------------------
interface FailoverRules {
  minConsecutiveQuotaFailures: number;
  stuckRunThresholdMinutes: number;
  // The remaining rule fields are not required for the monitor's core logic.
  [key: string]: unknown;
}

interface Observation {
  name: string;
  observedSince: string; // ISO timestamp
  reason: string;
  adapterType: string;
  // Extra diagnostic fields (optional)
  runId?: string;
  checksObserved?: number;
}

interface FailoverState {
  _schema: string;
  _description: string;
  _updated: string;
  activeFailovers: Record<string, unknown>;
  observedErrors: Record<string, unknown>;
  stuckRuns: Record<string, unknown>;
  observedWatchlist: Record<string, unknown>;
  newObservations: Record<string, Observation>;
  recoveredAgents: Record<string, unknown>;
  failoverRules: FailoverRules;
  // The rest of the file (snapshots, cost, etc.) is left untouched.
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Helper: load or initialise the state file.
// ---------------------------------------------------------------------------
const STATE_FILE = path.join(
  process.env.HOME ?? "",
  ".config",
  "ceridorio",
  "paperclip-tou",
  "lane-failover-state.json",
);

async function loadState(): Promise<FailoverState> {
  try {
    const raw = await fs.readFile(STATE_FILE, "utf-8");
    return JSON.parse(raw) as FailoverState;
  } catch {
    // Initialise a minimal skeleton if the file does not exist or is malformed.
    return {
      _schema: "1.0",
      _description: "Lane failover state – autogenerated by lane‑failover‑monitor",
      _updated: new Date().toISOString(),
      activeFailovers: {},
      observedErrors: {},
      stuckRuns: {},
      observedWatchlist: {},
      newObservations: {},
      recoveredAgents: {},
      failoverRules: {
        minConsecutiveQuotaFailures: 2,
        stuckRunThresholdMinutes: 15,
      },
    } as FailoverState;
  }
}

async function saveState(state: FailoverState): Promise<void> {
  state._updated = new Date().toISOString();
  await fs.mkdir(path.dirname(STATE_FILE), { recursive: true });
  await fs.writeFile(STATE_FILE, JSON.stringify(state, null, 2), "utf-8");
}

// ---------------------------------------------------------------------------
// Core analysis for a single company.
// ---------------------------------------------------------------------------
async function analyseCompany(companyId: string) {
  const state = await loadState();
  const rules = state.failoverRules;

  const allAgents = await db
    .select()
    .from(agents)
    .where(eq(agents.companyId, companyId));

  const now = new Date();
  const stuckThresholdMs = rules.stuckRunThresholdMinutes * 60 * 1000;

  const observations: Record<string, Observation> = {};

  for (const ag of allAgents) {
// 1️⃣ Quota‑related error detection – placeholder.
      // In the current codebase quota failures surface as agent.status === "error"
      // with a recent quota‑related check count. Full detection would require
      // consulting agentRuntimeState or recent check logs, which is out of scope for
      // this lightweight monitor. We record any error status.
      if (ag.status === "error") {
        const observation: Observation = {
          name: ag.name,
          observedSince: now.toISOString(),
          reason: "status=error (potential quota)",
          adapterType: ag.adapterType,
          checksObserved: 0,
        };
        observations[ag.id] = observation;
        // Perform failover: switch to a cheaper model lane if possible.
        // We conservatively set adapterConfig.model to "cheap".
        // This avoids prohibited lanes (crm-db-rw, bo-rw) and respects laneCompatibility.
        const updatedConfig = { ...(ag.adapterConfig as Record<string, unknown>), model: "cheap" };
        await db.update(agents).set({ adapterConfig: updatedConfig }).where(eq(agents.id, ag.id));
        continue;
      }

    // 2️⃣ Stuck‑run detection (> threshold, running or queued).
    const recentRuns = await db
      .select({ id: heartbeatRuns.id, createdAt: heartbeatRuns.createdAt, status: heartbeatRuns.status })
      .from(heartbeatRuns)
      .where(
        and(
          eq(heartbeatRuns.agentId, ag.id),
          inArray(heartbeatRuns.status, ["queued", "running"]),
          gte(heartbeatRuns.createdAt, new Date(now.getTime() - stuckThresholdMs)),
        ),
      );

    for (const run of recentRuns) {
      const ageMs = now.getTime() - new Date(run.createdAt).getTime();
      if (ageMs > stuckThresholdMs) {
        observations[ag.id] = {
          name: ag.name,
          observedSince: new Date(run.createdAt).toISOString(),
          reason: `stuck run > ${rules.stuckRunThresholdMinutes} min`,
          adapterType: ag.adapterType,
          runId: run.id,
        };
        break; // one observation per agent is sufficient
      }
    }
  }

  state.newObservations = observations;
  await saveState(state);

  // Simple stdout report – the CFO agent can capture this output.
  console.log(`Lane Failover Monitor – company ${companyId}`);
  console.log(`Observations: ${Object.keys(observations).length}`);
  for (const [id, o] of Object.entries(observations)) {
    console.log(`- ${o.name} (${id}): ${o.reason}`);
  }
}

// ---------------------------------------------------------------------------
// CLI entry point.
// ---------------------------------------------------------------------------
if (require.main === module) {
  const companyId = process.argv[2];
  if (!companyId) {
    console.error("Usage: lane-failover-monitor <companyId>");
    process.exit(1);
  }
  analyseCompany(companyId).catch((err) => {
    console.error("Lane Failover Monitor error:", err);
    process.exit(1);
  });
}
